### ISSUE TITLE
A few questions and suggestions

### ISSUE THREAD

**Issue by DanShappir** [ericelliott/rtype#10]
1. If I specify a default value for an arg, I shouldn't be required to specify a type. Instead, the type should be inferred. IMO a type should be specified in such a case only if the default value don't not specify the full type, e.g. any rather than number.
2. Given that the target is ES6+, why is ? needed for option args? Why isn't it enough to specify a default value to indicate an optional arg? Yes, this allows different implementations of the same interface, each using a different default, but that would be a bad practice IMO.
3. What's the value of a named return value? Can you give a concrete example of where it would be useful? Isn't the function name enough?
4. I would love for there to be a mechanism for specifying arguments as const and even frozen. Maybe too much to expect from something like rtype but still ...
5. Maybe a mechanism to specify whether a method modifies its instance or not, kind of like C++ const method modifier

**Comment by ericelliott** [comment]
1. Cool!
2. _"Why isn't it enough to specify a default value to indicate an optional arg?"_ We should infer that it's optional when there's a default. For others, `?` is useful for clarity, and so that we don't trigger type errors when they're missing.
3. _"What's the value of a named return value?"_ Mostly for clarification in documentation. Sometimes it can helpfully augment the function name and description. An example from the [Stamp Specification](https://github.com/stampit-org/stamp-specification): `stamp(options?: object, ...args?: any): instance: object`
4. _"specifying arguments as const and even frozen"_ Any ideas on how that would be represented? Maybe that should be default? ;)
5. _"Maybe a mechanism to specify whether a method modifies its instance or not"_ Not a bad suggestion. Again, I'd favor a does-not-modify default.

**Comment by DanShappir** [comment]
_"Any ideas on how that would be represented?"_ maybe like C++, e.g.

_function double(const n: number): number_

Alternatively, if you want to keep all declarations on the right-hand side:

_function double(n: const number): number_

Or borrowing another keyword from C++:

_function double(mutable n: number): number_

However, while I get where you're coming from, I think that enforcing const on arguments by default may confuse and turn off many JavaScript devs, It would be an interesting experiment ;-)

And for a non-modifying member:

_getValue(): value: const number_

BTW when a function is a procedure, i.e. does not return a value, do you need to specified _undefined_ as the return value?

One more thing the would be interesting to borrow from C++, although C++ payed a hefty price for it, is making the argument types part of the function signature. This enables overloading, but makes it more difficult to call functions from undercoated code.

**Comment by ericelliott** [comment]
> `getValue(): value: const number`

This looks good to me, with the stipulation that there's a difference between mutable/immutable and var/const.

> BTW when a function is a procedure, i.e. does not return a value, do you need to specified undefined as the return value?

I think if you want it to warn on any other value (accidental return?), that makes sense, right?

> function double(mutable n: number): number

There's a difference between `const` and immutable. In my mind, `mutable` implies that you can modify the referenced value, not just the variable assignment.

> making the argument types part of the function signature

One big problem with that is functions can have multiple function signatures. I think TypeScript accounts for that by allowing you to declare multiple function signatures per interface.

This is the idea I'm playing with for adding type metadata for [rfx](https://github.com/ericelliott/rfx#rfx):

``` js
rfx({
  t: [
    sig`(...args: obj[]): obj`,
    sig`(input: string): foo`,
    rt`interface foo { bar: string }`
  ],
  fn (input, ...args) { /* ... */ }
});
```

**Comment by stonehippo** [comment]
> In my mind, mutable implies that you can modify the referenced value, not just the variable assignment.

Right. You're signaling whether the function will mutate the referenced value (object, array) passed to it. Does mutable have meaning for a function that takes on basic types as parameters (e.g number, string)? Pass by value pretty much prevents mutation of the parameters outside of function scope.

> getValue(): value: const number

What does this signal? I can't think of why I would want to specify such a thing. Unless it's intended for documentation purposes, in which case, I feel like I'd want to be more specific about the expected const in same way.

**Comment by tomek-he-him** [comment]
> > getValue(): value: const number
> 
> What does this signal? I can't think of why I would want to specify such a thing. Unless it's intended for documentation purposes, in which case, I feel like I'd want to be more specific about the expected const in same way.

Yeah, I’m quite confused by this syntax as well.

Perhaps we could allow JS-style comments in signatures?

``` js
getValue(): const number  // The returned value
```

**Comment by ericelliott** [comment]
@DanShappir

I think it may make sense to declare whether or not something is mutable in the parameters list, but what does it mean for a return value?  If it means that it's frozen, it should probably say `frozen` instead of `const`?

**Comment by Mouvedia** [comment]
**1** :+1: 

 **4** 
- isConst
- isExtensible, isSealed and isFrozen

**Comment by ericelliott** [comment]
Does a signature need to know about `const` at all? `mutable` or `mutates` maybe...?

For return values, `extensible` is default, so maybe not needed at all. `sealed` and `frozen` make sense.

**Comment by tomek-he-him** [comment]
> Does a signature need to know about const at all? mutable or mutates maybe...?

:+1: `const` (strictly speaking `notTouched` or `notMutated`) should definitely be the default!

**Comment by ericelliott** [comment]
Yeah, I think it's useful to call out whether or not an argument gets mutated, but `const` doesn't mean immutable, it means that it can't be reassigned. But that's not a concern that outside code needs to know about.

**Comment by stonehippo** [comment]
+1 on `mutable`, with perhaps an optional (default?) `immutable`.

And yeah, `const` definitely feels wrong. Too hard to understand how it relates a constant declaration (it really doesn't).

**Comment by tomek-he-him** [comment]
> +1 on mutable

How about `mutated`?
- `mutable` doesn’t imply that an object will be _mutated_.
- It’s OK to pass a _mutable_ array to a function which doesn’t mutate it. (Think `[1, 2, 3].map(…)`.)

**Comment by stonehippo** [comment]
@tomekwi yes, that makes senses

**Comment by ericelliott** [comment]
@tomekwi :+1:

**Comment by ericelliott** [comment]
Let's see some examples of `mutated` in signatures. Bring on the dream code. =)

**Comment by jokeyrhyme** [comment]
> How about `mutated`?
> - mutable doesn’t imply that an object will be mutated.

What about a function that may or may not mutate its arguments? e.g. a stable sort function

What are we trying to communicate when we use either `mutated` or `mutable` keywords in a signature? For me, it's very useful to know if a function can be used with functional-style code or not, so just the possibility of mutation (i.e. `mutable`) achieves this.

**Comment by ericelliott** [comment]
> For me, it's very useful to know if a function can be used with functional-style code or not, so just the possibility of mutation (i.e. mutable) achieves this

Good point. :+1:

**Comment by Mouvedia** [comment]
Were all initial questions resolved?
Is there a consensus on what should be added?
If not what are the issues that still need to be addressed?

**Comment by ericelliott** [comment]
I don't think we've added a `mutable` keyword, yet.

**Comment by ericelliott** [comment]
Let's close this and open individual issues if there are remaining issues outstanding.
