### ISSUE TITLE
object literal types and enumerations

### ISSUE THREAD

**Issue by maiermic** [ericelliott/rtype#100]
A [literal type](https://github.com/ericelliott/rtype#literal-types) is a value that is also a type with only the value as member. The documentation mentions `String` and `Number` literals:

``` js
signatureName(param1: String, param2: 'value1' | 'value2' | 'value3') => -1 | 0 | 1
```

Object literals (e.g. `{}`) might be used as type, too. Unlike `String` and `Number` literals, object literals are not equal:

``` js
{} === {} // false
```

Therefore, object literals have to be treated different. Each object literal defines it's own type.
## Example

Object literals might be used to describe an enumeration type `Weekday`

``` js
interface Weekday: Monday | Tuesday | Wednesday | Thursday | Friday | Saturday | Sunday
```

which might be defined like this

``` js
const Monday = {};
const Tuesday = {};
const Wednesday = {};
const Thursday = {};
const Friday = {};
const Saturday = {};
const Sunday = {};
```

which might be used in a function `isWeekend`

``` js
isWeekend(Weekday) => Boolean
```

that might look like this

``` js
function isWeekend(day) {
  return (Saturday === day || Sunday === day);
}
```

Since those values belong together, they might be grouped as an object

``` js
const Weekday = {
  Monday: {},
  Tuesday: {},
  Wednesday: {},
  Thursday: {},
  Friday: {},
  Saturday: {},
  Sunday: {}
};
```

or similar as a module:

**Weekday.js**

``` js
module.exports = {
  Monday: {},
  Tuesday: {},
  Wednesday: {},
  Thursday: {},
  Friday: {},
  Saturday: {},
  Sunday: {}
};
```

In other languages (Java, TypeScript, etc.) this is called an enumeration (short _enum_). We can type this object as `enum Weekday`

``` js
// enum Weekday
const Weekday = {
  Monday: {},
  Tuesday: {},
  Wednesday: {},
  Thursday: {},
  Friday: {},
  Saturday: {},
  Sunday: {}
};
```

where `enum Weekday` is an abbreviation for

``` js
interface Monday
interface Tuesday
interface Wednesday
interface Thursday
interface Friday
interface Saturday
interface Sunday

interface Weekday: Monday | Tuesday | Wednesday | Thursday | Friday | Saturday | Sunday

interface WeekdayEnum {
  Monday: Monday,
  Tuesday: Tuesday,
  Wednesday: Wednesday,
  Thursday: Thursday,
  Friday: Friday,
  Saturday: Saturday,
  Sunday: Sunday
}
```

resulting in

``` js
// WeekdayEnum
const Weekday = {
  Monday: {},
  Tuesday: {},
  Wednesday: {},
  Thursday: {},
  Friday: {},
  Saturday: {},
  Sunday: {}
};
```

Since an enumeration is a set (union) of types, we can express subsets using the same types:

``` js
interface WorkingDay: Monday | Tuesday | Wednesday | Thursday | Friday

interface WeekendDay: Saturday | Sunday
```

Thus, we can define `Weekday` as:

``` js
interface Weekday: WorkingDay | WeekendDay
```

**Comment by Raynos** [comment]
your example would be better with string literals

**Comment by maiermic** [comment]
I admit, this example is not the best, but some people prefer object literals due to easier refactoring. I like to type such code, too.

**Comment by Raynos** [comment]
This makes a lot of things really hard.

Your effectively adding nominal typing to a structural type system. Previously all interfaces were just sugar that could be denormalized into a single structural type.

**Comment by ericelliott** [comment]
Nominal types, meaning identity or name-based types, are generally not a good fit for JavaScript because it's common to use interfaces across execution contexts (such as iFrames, web workers, etc...). Identity based type checks produce false negatives across such contexts, whereas structural type checks work fine.

Keep in mind that rtype is intended to be usable for runtime checks, so even if there's a way to get around such issues in static analysis, such a feature would cause undesirable runtime behavior.

This:

``` js
interface Weekday: Monday | Tuesday | Wednesday | Thursday | Friday | Saturday | Sunday
```

Is less reliable than this:

``` js
interface Weekday: 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday'
```

**Comment by Mouvedia** [comment]
@maiermic check http://speakingjs.com/es5/ch08.html#id1061835

It doesn't take into account symbols but it should clarify some things for you. In short I disagree on the premise.

**Comment by maiermic** [comment]
You are all right. It is a bad idea.
