### ISSUE TITLE
max arity

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#103]
tl;dr: checks that `arguments.length` doesn't exceed a certain limit

inspired by: https://www.eventbrite.com/engineering/learning-es6-rest-spread-operators/#enforcing-maximum-arity

I don't have a proposal yet.

**Comment by Mouvedia** [comment]
Just to jump-start the discussion, here are some suggestions:
1. the `{}` quantifier
2. [the `..` operator](https://coffeescript-cookbook.github.io/chapters/arrays/define-ranges) (inclusive range)

```
// exactly 5
(...: [...Any]){5} => ReturnType

// minimum 2, maximum 4
(...args: [...Any])2..4 => ReturnType

// minimum 2
(...args: [...Any])2.. => ReturnType

// maximum 4
(...args: [...Any])..4 => ReturnType
```

**Comment by maiermic** [comment]
Rest parameters are arrays. Arrays with minimum or maximum arity are similar to typed arrays described in #96 and #102.

``` js
// exactly 5
(...: [Any, Any, Any, Any, Any]) => ReturnType

// minimum 2, maximum 4
(...args: [Any, Any]) => ReturnType
(...args: [Any, Any, Any]) => ReturnType
(...args: [Any, Any, Any, Any]) => ReturnType

// minimum 2
(...args: [Any, Any, ...Any]) => ReturnType

// maximum 4
(...args: [Any]) => ReturnType
(...args: [Any, Any]) => ReturnType
(...args: [Any, Any, Any]) => ReturnType
(...args: [Any, Any, Any, Any]) => ReturnType
```

This gets kind of verbose. Especially in case of maximum arity and depending on the amount of arity.

Do we really need syntax sugar to reduce verbosity of those cases? Even though it's verbose, I find it quite readable.

**Comment by maiermic** [comment]
By the way, we don't need typed arrays for those examples:

``` js
// exactly 5
(Any, Any, Any, Any, Any) => ReturnType

// minimum 2, maximum 4
(Any, Any) => ReturnType
(Any, Any, Any) => ReturnType
(Any, Any, Any, Any) => ReturnType

// minimum 2
(Any, Any, ...args: [...Any]) => ReturnType

// maximum 4
(Any) => ReturnType
(Any, Any) => ReturnType
(Any, Any, Any) => ReturnType
(Any, Any, Any, Any) => ReturnType
```

**Comment by Mouvedia** [comment]
OK then let's take a different approach. Is it really the job of rtype to make sure that we don't have more than 10 arguments passed?

By convention functions don't have more than 4 arguments.
That means that:
- it will probably be picked by your linter (max-params rule)
- it's way too rare to warrant being added to rtype
- if we have 4 or less it's not that bothersome to be explicit

@maiermic concerning your first comment, overloading doesn't exist in JS so your maximum examples are not proper replacements. Concerning your second comment, the presence of a parameter in a function declaration doesn't entails the function body to not accept/use more or less of them, even if it's not recommended. It's the job of a linter to know that a parameter is not used for example. As an exercice you can try to check `arguments.length` when you explicitly pass `undefined`.

And lastly there's a conflict in the intent:

```
// this is 0 or more of type Any but it's not? It's 2, 3 or 4
// that means ... and {} are incompatible
(...args: [...Any{2,4}]) => ReturnType
```

What about:

```
// minimum 2, maximum 4
(...args: [Any{2,4}]) => ReturnType
```

?

That would introduce a restriction to rest parameters. Is the complexity burden still worth it?

**Comment by maiermic** [comment]
@Mouvedia 

> overloading doesn't exist in JS

Maybe we understand different things by the term overloading. IMO rtype allows overloading of type signatures like [this](https://github.com/ericelliott/rtype#interface-user-defined-types):

> For polymorphic functions, use multiple function signatures:
> 
> ``` js
> interface Collection {
>   (items: [...Array]) => [...Array],
>   (items: [...Object]) => [...Object]
> }
> ```

As well as TypeScript. At least, I would call [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery/jquery.d.ts#L662) definition of jQuery's Ajax GET as overloaded function:

> ``` TS
> /**
>  * Load data from the server using a HTTP GET request.
>  *
>  * @param url A string containing the URL to which the request is sent.
>  * @param success A callback function that is executed if the request succeeds.
>  * @param dataType The type of data expected from the server. Default: Intelligent Guess (xml, json, script, or html).
>  */
> get(url: string, success?: (data: any, textStatus: string, jqXHR: JQueryXHR) => any, dataType?: string): JQueryXHR;
> /**
>  * Load data from the server using a HTTP GET request.
>  *
>  * @param url A string containing the URL to which the request is sent.
>  * @param data A plain object or string that is sent to the server with the request.
>  * @param success A callback function that is executed if the request succeeds.
>  * @param dataType The type of data expected from the server. Default: Intelligent Guess (xml, json, script, or html).
>  */
> get(url: string, data?: Object|string, success?: (data: any, textStatus: string, jqXHR: JQueryXHR) => any, dataType?: string): JQueryXHR;
> /**
>  * Load data from the server using a HTTP GET request.
>  *
>  * @param settings The JQueryAjaxSettings to be used for the request
>  */
> get(settings : JQueryAjaxSettings): JQueryXHR;
> ```

**Comment by Mouvedia** [comment]
@maiermic that's an interface. Your example had stacked-up function signatures. If your alternative is an interface with variants of a signature repeated n number of times, Id say it's not really elegant or practical.

**Comment by jokeyrhyme** [comment]
Might be better to define a tuple interface with a name first, then use that name in the function signature. Doing it inline seems convenient but looks like it would get hard to read.

**Comment by Mouvedia** [comment]
I think this is not warranted at this stage and would introduce uncalled complexity.
[max-params](http://eslint.org/docs/rules/max-params) will do the job just fine.
