### ISSUE TITLE
Doc generation promotion

### ISSUE THREAD

**Issue by js-jslog** [ericelliott/rtype#104]
I feel like the functional benefits are already sufficiently defined to be drawing serious attention to rtype, even this far ahead of a production release. In terms of convincing people of it's suitability as a replacement for JSDoc though, I think we need some more examples / thought on it's capacity as the base of a doc gen specification.

There are three things that I would like to raise for further discussion.
1. Potential for rtype definitions above function blocks.
   The rfx framework will enforce type checking using rtype definitions, and people can write rtypes into their specifications for descriptive purposes (like stampit). However, including an rtype definition above a function for JSDoc style scanning and extraction would be great too. It's not clear to me that there is a plan to support this.
2. The potential inter-relatability of objects within the application
   rtypes, by nature, will do a great job of representing the types involved in a function, and with 'requires' & the potential use of type aliases (#98), the relationship between functions and the objects they produce has rich (and wikilinked) documentation potential. I don't think enough of a point has been made of this, with attention (understandably) focused on the cleanness of the signature representation.
3. Function descriptions along with rtype definitions
   I notice that rfx interface definitions include a 'description' & 'doc' property. I assume any rtype based documentation specification would include similar capabilities.

I'm sure there's a good chance that these things are already being considered, in which case they probably just need to be more clearly defined in the readme.

**Comment by ericelliott** [comment]
It sounds like you're asking for [rfx](https://github.com/ericelliott/rfx) -- but in some other form (like comments?)
1. I prefer something like [rfx](https://github.com/ericelliott/rfx) for this, but I don't see any reason that putting rtype signatures in comments above functions should be unsupported.
2. Again, [rfx](https://github.com/ericelliott/rfx) enshrines that relationship in code.
3. Yeah. This is what [rfx](https://github.com/ericelliott/rfx) is for, but we also need to support the use of `.rtype` files, which we have discussed before (think C header files).

I'm open to suggestions, with the caveat that all of these have already been considered in [rfx](https://github.com/ericelliott/rfx), and the runtime capabilities that [rfx](https://github.com/ericelliott/rfx) will enable that comments _could not_ are quite interesting.

Runtime capabilities are a big part of the motivation for rtype, and if you dismiss rfx too quickly in favor of JSDoc style comments, you'll miss out on a lot of the power that rtype could provide. See the [Node Machine project](http://node-machine.org/) for inspiration.

**Comment by js-jslog** [comment]
Thanks for clearing that up @ericelliott. I now see that a _comment-style_ documentation spec built around rtype is not a consequential part of either the type or rfx projects.

I think the benefits of such a project are well worth considering though. I for one was very excited about the possibility (as I misinterpreted it) of commenting up existing code with an rtype based doc spec, immediately benefit from more readable doc comments and look forward to the powerful doc generation mentioned above.

rfx looks to have a powerful potential and it may be used widely where applicable, but if there is a way to make rtypes accessible to everyone, with further power to those using rfx as well then all the better I think.

**Comment by ericelliott** [comment]
Yep. That's the plan. Feel free to contribute to it. =)

**Comment by js-jslog** [comment]
Great. I'll have a play

**Comment by Mouvedia** [comment]
It seems that the discussion is over and your issues were addressed by @ericelliott's comment.
We might have to track the support of .rtype files in a new issue though.

If you have subsequent suggestions you could probably open a new issue on [rfx](https://github.com/ericelliott/rfx) repository.
