### ISSUE TITLE
How to annotate an object which properties should be of a certain type?

### ISSUE THREAD

**Issue by koresar** [ericelliott/rtype#105]
My object values must be RegExp only. But the keys can be anything, no limitations:

``` js
{
  foo: new RegExp(),
  bar: new RegExp()
}
```

How to annotate that all the values must be of the RegExp type?

P.S.
Like that I suppose?

```
Object[String,RegExp]
```

**Comment by Mouvedia** [comment]
`RegExp`
https://github.com/ericelliott/rtype#builtin-types
https://github.com/ericelliott/rtype/pull/42/files#r59980276

Concerning the syntax it's currently being discussed in several issues.
cf #97

**Comment by koresar** [comment]
Thanks @Mouvedia 👍
