### ISSUE TITLE
Declaring rtype's aim(s)

### ISSUE THREAD

**Issue by koresar** [ericelliott/rtype#106]
It's a good idea to declare rtype's evolution directions. Currenly all we have is:

> - Great for simple documentation.
> - Compiler-agnostic type notation - for use with ECMAScript standard tools.
> - Can embed in JS as strings, for example with rfx. Affords easy runtime reflection.
> - Standing on the shoulders of giants. Inspired by: ES6, TypeScript, Haskell, Flow, & React

It lacks something like:
1. Aim to provide low learning curve for JS devs. **Or,**
2. Aim to provide better syntax than any other language.

@ericelliott could you please voice your suggestion here?

I personally would vote for **1**.

**Comment by Mouvedia** [comment]
- low learning curve for JS developers

Should be a statement: no place for uncertainty.

**Comment by ericelliott** [comment]
1
