### ISSUE TITLE
Specifying getters & setters

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/rtype#108]
It should be possible to document that something is a getter or setter, rather than a simple typed value. For example:

``` js
createUser({ name, age }) => {
  name: String,
  get isAdult() => Boolean
}
```

**Comment by Mouvedia** [comment]
Are you talking about the accessor descriptors?
AFAIK getters don't accept parameters; should we keep the `()` in that case?

**Comment by ericelliott** [comment]
I'm talking about [getters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) and [setters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set).

> AFAIK getters don't accept parameters; should we keep the () in that case?

Hmm.. maybe not! This is probably fine for getters:

``` js
createUser({ name, age }) => {
  name: String,
  get isAdult => Boolean
}
```

Actually... now that I'm looking at it, that looks like a function called `get` that takes a parameter, `isAdult` and returns a `Boolean`.... that's awkward.

**Comment by Mouvedia** [comment]
I am not proposing, I am asking.
The real deal breaker for the alternate would be the consistency; since you can't have a setter without an argument IIRC.

**Comment by ericelliott** [comment]
Sounds like 2 good reasons to always use parens. =)

**Comment by Mouvedia** [comment]
What would it look like with a setter which signature is inlined?
Id like to know where you would put the type of the parameter. If it's not inside the parens of the set then we can discard them. In that case it would match exactly what we have in ES5.

**Comment by ericelliott** [comment]
``` js
createUser({ name, age }) => {
  name: String,
  get isAdult() => Boolean,
  set age(age: Number)
}
```

Note that for setters, it doesn't make sense to specify a return value, so we leave the return type off.
