### ISSUE TITLE
How to handle successive optional parameters?

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#111]
Optional parameters are often represented using brackets which helps when you have consecutive optional parameters.
e.g. `name(arg1 [, arg2 [, arg3]])`

We need a way to convey that nesting/precondition as well.
Here are some proposals which reuse `?` as an infix:

```
// parentheses A
signatureName(param1: Type, ?(param2: Type,  ?(param3: Type))) => Type

// parentheses B
signatureName(param1: Type ?(, param2: Type ?(, param3: Type))) => Type

// brackets A
signatureName(param1: Type, ?[param2: Type,  ?[param3: Type]]) => Type

// brackets B
signatureName(param1: Type ?[, param2: Type ?[,  param3: Type]]) => Type
```

**Comment by ericelliott** [comment]
What's wrong with this?:

``` js
signatureName(param1: Type, param2?: Type,  param3?: Type) => Type
```

**Comment by Mouvedia** [comment]
@ericelliott that doesn't convey that the second parameter is _not_ optional if the third is present: that you have to add a placeholder.

**Comment by ericelliott** [comment]
@Mouvedia If I were in that situation, I would combine the second and third parameters into a single object:

``` js
interface GroupedType {
  param2: Type,
  param3: Type
}

signatureName(param1: Type, groupedParams?: GroupedType) => Type
```

The advantages:
- Takes advantage of existing syntax. 
- Syntax is very clear and readable, unlike the examples above.

**Comment by Mouvedia** [comment]
All the proposals—including mine—are not elegant or intuitive.

**Comment by Mouvedia** [comment]
@ericelliott your proposal reminds me of [that](http://stackoverflow.com/a/30734743/248058).

**Comment by ericelliott** [comment]
The best solution for that problem, IMO:

``` js
error({ message: String, title?: String, autoHideAfter? : Number });
```

**Comment by ericelliott** [comment]
Closing because the proposal is more confusing than the existing solutions.
