### ISSUE TITLE
method overloading

### ISSUE THREAD

**Issue by Raynos** [ericelliott/rtype#114]
I'm not sure if method overloading is specced but doing so would be very useful.

I've just implemented method overloading in `jsig` and it really helps

Using a field with the `&` intersection expression.

``` hs
type MyEvents : {
    on: (
        ((this: MyEvents, str: "key1", cb: (String) => void) => void) &
        ((this: MyEvents, str: "key2", cb: (Number) => void) => void) &
        ((
            this: MyEvents,
            str: "key3",
            cb: ({ a: String }) => void
        ) => void)
    )
}
```

Using method overloading syntax

``` hs
interface MyEvents {
    on(str: "key1", cb: (String) => void) => void,
    on(str: "key2", cb: (Number) => void) => void,
    on(str: "key3", cb: ({ a: String}) => void) => void
}
```

There may be an even nicer way to represent method overloading but not having to worry about braces and the problem of is `&` for the **function** or is `&` for the **return type** of the function is a really big win.

Also quite a lot of folks are confused about whether method overloading is `&` or `|`, by simply having repeated syntax thats familiar this confusion is reduced.

**Comment by ericelliott** [comment]
Specced under [Function Interface](https://github.com/ericelliott/rtype#function-interface). See also this [related proposal](https://github.com/ericelliott/rtype/issues/113).

We don't call it "method overloading" because any function can have a polymorphic type.

**Comment by Mouvedia** [comment]
It seems that he is enquiring about _inline_ "method overloading". @Raynos am I correct in assuming that you don't want to separate the definition—to reuse it or help the readability?

**Comment by Raynos** [comment]
@Mouvedia 

Correct, any given interface that has many methods and fields, should allow for multiple methods to be optionally overloaded.

For example: 

```
interface MyEvents {
    _events: Object<String, Function>,

    on(str: "key1", cb: (String) => void) => void,
    on(str: "key2", cb: (Number) => void) => void,
    on(str: "key3", cb: ({ a: String}) => void) => void,

    emit(str: "key1", String) => void,
    emit(str: "key2", Number) => void,
    emit(str: "key3", { a: String }) => void,

    removeListener(String, Function) => void,
    removeAllListeners() => void
}
```

**Comment by ericelliott** [comment]
Ah, I see. Yes, I like this. 👍 

I also don't see any problem with the suggested syntax. Please feel free to PR.

**Comment by Mouvedia** [comment]
@ericelliott Iv got 2 other PRs coming before Ill take this one in hand.
@Raynos if you PR we need to know if we are lax about the position of the signatures first. In short ought the signatures be consecutive or not. Id vote for anywhere goes to allow stuff like:

```
interface Foo {
  (Type) => Type,

  a(Object) => Void,
  b(Object) => Void,
  c(Object) => Void,

  a(String, Number) => Void,
  b(String, Number) => Void,
  c(String, Number) => Void
}
```

**Comment by Raynos** [comment]
@Mouvedia 

My implementation loops over all fields & methods ( https://github.com/Raynos/jsig/blob/master/parser/type-declaration.js#L62-L96 ) and builds up an index.

So order does not matter.

I think grouping them together by methodName really improves readability though, especially if the interface definition is >100 lines.

**Comment by Mouvedia** [comment]
@Raynos great! Hopefully the rtype branch will get some lovin'. In the long run the goal is to have something to show for it. There's definitely a demand for #89.

**Comment by ericelliott** [comment]
Is there a PR for this yet? I like it.

**Comment by Mouvedia** [comment]
I was waiting for #115 to be merged so that we wouldn't have conflicts.

**Comment by Mouvedia** [comment]
@ericelliott #121
