### ISSUE TITLE
Should we add a JSON reserved type?

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#116]
Of course we would have to pick one of the RFCs or ECMA-404 as the basis of what is JSON. In that regard the latest is not always the best choice, sadly.

**Comment by ericelliott** [comment]
JSON is a string that can't be type checked without parsing it, which could be performance draining... Are we sure this is needed?

**Comment by Mouvedia** [comment]
@ericelliott this is labelled _question_, and it's not rhetorical.

I sense that there might be a need to document that. In 2006, I probably would have asked for something like `Document` because, back then, XML was the "data-interchange language" of choice.

Is it out of scope?

**Comment by ericelliott** [comment]
Probably.

**Comment by Mouvedia** [comment]
JSON isn't a type but a format.

If anything it could be an extension on top of rtype which would support [popular data-exchange languages](https://en.wikipedia.org/wiki/Data_exchange#Popular_languages_used_for_data_exchange). It shouldn't be part of the core.
