### ISSUE TITLE
Type name convention

### ISSUE THREAD

**Issue by tomek-he-him** [ericelliott/rtype#13]
Hi Eric,

since `Function` starts with a capital letter, why not say all types should start with a capital?

I’m used to a convention that a type is referenced by the name of its constructor. `String` for strings because `'abc' instanceof String` and `Array` for arrays because `[1, 2, 3] instance of Array`. Basing the convention off the output of `typeof` is flaky – for example because `typeof [1, 2, 3] === 'object'`.

Then all type names would be consistent. Much easier to scan. Try scanning these two signatures quickly:

``` js
(
  number: string,
  boolean: MyTypeCapital,
  array: myTypeLowercase,
  object: Function,
  string: number,
): number: string

(
  number: String,
  boolean: MyTypeCapital,
  array: MyTypeLowercase,
  object: Function,
  string: Number,
): number: String
```

Oh, and you get syntax highlighting for free!

**Comment by ericelliott** [comment]
I agree. I used lowercase for compatibility with TypeScript.

But I'm not sure TypeScript compatibility is the right goal. Consistency should probably win.

**Comment by Mouvedia** [comment]
+1 on consistency.

**Comment by tomek-he-him** [comment]
:+1: great! Personally I’ve never used TypeScript. But looking at [one of the official examples](https://github.com/Microsoft/TypeScriptSamples/blob/master/raytracer/raytracer.ts) type identifiers look like a mess!

**Comment by ericelliott** [comment]
I'm open to a PR.

**Comment by ericelliott** [comment]
We don't have the same restrictions as TypeScript, since our signatures will be inside strings. I think our types should match the name of the function that generates them.

**Comment by tomek-he-him** [comment]
:+1:

Expect a PR soon then!

**Comment by ericelliott** [comment]
Cool! =)
