### ISSUE TITLE
inlined instance methods

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#138]
I wanna revisit https://github.com/ericelliott/rtype/pull/27#commitcomment-14551857.

e.g.
```js
interface example {
  (signatureParam: Any) => Any,
  #method() => Any // example.prototype.method
}
```

`#` is the shorthand for `.prototype.`; I dunno how well spread/known this prefix notation is. It should be noted that it could be confused with [private fields](https://github.com/tc39/proposal-class-fields#private-fields).

@ericelliott Do you have an alternative that wouldn't conflict with the upcoming class fields proposal?

**Comment by ericelliott** [comment]
I think we need to wait to see what the ECMAScript community does with `class` before we add shorthand syntax to the spec that may eventually conflict.

In the meantime, you should treat the instance and the class/factory/constructor as separate interfaces.

You can also treat the prototype as a separate interface if you want to be explicit that a method should exist on the prototype, but NOT on the instance.

Let's table this until there's significant progress here from ECMA.
