### ISSUE TITLE
News ?

### ISSUE THREAD

**Issue by hugomallet** [ericelliott/rtype#148]
Hi,

I was looking for an alternative to TypeScript and I've found this project.
A type system looks handy for development tools and certainly avoid some simple errors.

TypeScript is very good in this and very famous now. When looking at the documentation of TS the fist time, i read about interfaces and was thinking, wow great ! Interfaces are just shapes. Very good idea.  

But then I was so disappointed when I saw generics and "class implements" ... Why do people think we need it ? They just add the complexity we always wanted to leave when working with Java, C# etc... And beginners cry for each generic they see (I'm teaching).

So I was looking for a language compatible with TS (in order to benefit from the existing type definitions) but without the C# stuff. And optionally a language that would compile to a dynamic type checker like PropTypes (or here rfx). 

This project was created 5 years ago. Looks like I'm very late...
It does not look maintained anymore. Is this idea still relevant ? or completely abandoned ? 

Best

**Comment by Raynos** [comment]
In terms of active type checkers as alternatives to typescript you can check out facebook flow or https://hegel.js.org/

**Comment by hugomallet** [comment]
Thanks @Raynos . I knew them but they share the same philosophy of TS : complex type definitions. So not what I was looking for.

**Comment by Mouvedia** [comment]
@hugomallet you should check #89
Concerning the status of the project Ill let @ericelliott chime in for an official statement.

**Comment by ericelliott** [comment]
This project is not an active alternative to TypeScript because nobody has written feature-complete, well-maintained tooling for it. I use it for documentation.

**Comment by hugomallet** [comment]
Hi everyone,

Thanks @ericelliott for the status update.

@Mouvedia, I'm not sure I understand completely the context of the issue #89 but it looks like that it becomes quickly very complicated as soon as we decide to implement a "generic-like" type checking.

I agree that this is elegant and type safe :
```ts
const result: Result = await new Promise<Result>(...);
```
But when I look at the [source file of Promise in TS](https://github.com/microsoft/TypeScript/blob/master/src/lib/es2015.promise.d.ts), it grinds my gears :exploding_head:, this is totally unreadable.
And this is not the more complicated type definition in the TS ecosystem, especially with the last features...

I'm looking for a happy medium but it may be an utopia. I keep my beloved untyped JS for now.  

Thanks all,

**Comment by ericelliott** [comment]
@hugomallet Yep. I use rtype almost every day for documentation purposes, and I use the TypeScript type-inference engine (via VSCode) on standard JavaScript (not TypeScript).

I use a variant of rtype which may not be fully documented - the variant supports higher kinded types, so I can write stuff like:

```
// type map = (f: a => b) => mappable(a) => mappable(b)
```
