### ISSUE TITLE
Add an example of an unnamed parameter

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#18]
> Optionally, you may name the return value, similar to named parameters:
> (param: Type) => name: Type

This implies that parameter names are also optional.
Ill take as an example the documentation of one my repo that I plan to switch to rtype.

```
String.isString(Any) => Boolean
```

In this case there's no way to name the parameter accurately.

**Comment by ericelliott** [comment]
:+1: PR?

**Comment by Mouvedia** [comment]
#19
