### ISSUE TITLE
type inferred on the default

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#26]
We need an example where the type is derived from the value of the default.
You don't have to be explicit about it in this case.

```
( count = 0 )
//would be equivalent to
( count = 0: Number )
```

Slightly off topic
@ericelliott If you have a function that always return the same value can you do something like

```
( param ) => String = 'example'
//or
( param ) => 'example': String

//shorthand
( param ) => 'example'
```

?

**Comment by tomek-he-him** [comment]
> If you have a function that always return the same value

…or if you have a function which always _expects_ the same value on a property. For example @Matt-Esch does that on _virtual-dom_ to ensure backwards-compat: https://github.com/Matt-Esch/virtual-dom/blob/903d884a8e4f05f303ec6f2b920a3b5237cf8b92/vnode/vnode.js#L71-L72.

This would be a trickier one because `=` is already taken in param context.

**Comment by ericelliott** [comment]
The spec already has support for native type literals, including both parameters and return values.

``` js
(someThing: 'SpecificThing') => 'Always returns this string';
```

**Destructuring parameter exceptions:** To disambiguate from destructuring, only simple type literals are supported in parameters:

``` js
wrong(thing1: { a: 'a' }, thing2: [ 'b' ]) => Any
```

``` js
interface A:  { a: 'a' }
interface B: [ 'b' ]
better(thing1: A, thing2: B) => Any
```

I'm willing to look at a PR to clarify.

**Comment by Mouvedia** [comment]
@ericelliott This issue is not about that. Thanks for the clarification though.

**Comment by ericelliott** [comment]
Oh, I see. We need to explicitly document that we can infer types from default values. Yes. Feel free to PR. =)

**Comment by Mouvedia** [comment]
@ericelliott  #32

Ill let you add the part about the return values with a constant value.
