### ISSUE TITLE
Inconsistency in `throws` doc

### ISSUE THREAD

**Issue by amelon** [ericelliott/rtype#29]
In doc below, first example show a `:` after `throws`

In last example, `:` vanished. 

I don't know which one is correct.
### Throwing functions

To indicate that a function can throw an error you can use the `throws` keyword.

``` js
functionName() => String, throws: TypeError|DOMException
```

For the generic `Error` type, you can optionally omit the throw type:

``` js
functionName() => String, throws
```

Is equivalent to:

``` js
functionName() => String, throws Error
```

**Comment by Mouvedia** [comment]
51f555c0837b8068b95235843a8edbf5ffbe0bec

**Comment by ericelliott** [comment]
Thanks! :+1:
