### ISSUE TITLE
Enum

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#31]
Do you have enums?
I think it would be useful.

**Comment by tomek-he-him** [comment]
What do enums look like in JS? I’ve tried things like

``` js
export const modes = {
  ON: Symbol('ON'),
  OFF: Symbol('OFF'),
};
```

– but it never seemed particularly easy to use.

**Comment by Mouvedia** [comment]
I didn't have that in mind when I talked about enum.
Here's the use case:

```
functionName(param1: String, param2: 'type1' | 'type2' | 'type3')
```

This function only accepts theses strings for the second parameter.
Another example would be a function that returns only `0`, `1` and `-1`.

**Comment by tomek-he-him** [comment]
If I correctly understand what @ericelliott said in https://github.com/ericelliott/rtype/issues/26#issuecomment-158695876, then what you propose is already valid syntax.

**Comment by Mouvedia** [comment]
Then we need an example of that in the union section.

**Comment by ericelliott** [comment]
**How about something like this?:**

You can use unions and the built-in support for literal types to create enum types, meaning that the value must match one of the literal values in the union:

``` js
functionName(param1: 'value 1' | 'value 2' | 'value 3') => Any
```

**Comment by ericelliott** [comment]
Feel free to PR.

**Comment by Mouvedia** [comment]
@ericelliott #34
