### ISSUE TITLE
Predicate function as interface

### ISSUE THREAD

**Issue by tomek-he-him** [ericelliott/rtype#33]
If I understand the spec correctly, I can’t specify types like `Integer` through `interface` directly in the signature string. What do you guys think about this then:

``` js
type Integer (number) => (
  number === parseInt(number, 10)
)
```

**Comment by Mouvedia** [comment]
Personally I like it but it should be buried in the documentation.

**Comment by ericelliott** [comment]
I think this should work already (function literal):

``` js
interface Integer (number) => number === parseInt(number, 10)
```

Does that sound good?

**Comment by tomek-he-him** [comment]
:+1: :+1: Great! Thanks!!!
