### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#35]
I dunno if it's on scope for rtype but I will ask anyway: is there any way to list the dependencies of a function?
If leveraged it's an information that can help inject beforehand—and only once—the dependencies accordingly.

Ill give you a real example: String.parseAsId _and_ String.parseAsClass both use String.prototype.inspect and String.isString. This should be documented somehow.

**Comment by ericelliott** [comment]
Can you give a more concrete example? Show code? Or at least pseudocode example?

**Comment by Mouvedia** [comment]
```
String.parseAsClass(className: String , HTML5: Boolean)
  => Void,
  throws: SyntaxError | TypeError | DOMException,
  requires: [String.prototype.inspect, String.isString]

// one dependency
functionName() => Type, requires: anotherFunction
```

--- off topic ---
We could have `=>` aliased to `returns`:

```
A()
  returns: Type,
  throws: ErrorType
  requires: B
```

**Comment by jokeyrhyme** [comment]
It would be pretty neat to be able to (eventually) generate a minimum poly-fill required for each target environment, assuming all my functions have their ES5 and ES2015 API dependencies noted.

Or even being able to provide library consumers with automatically generated browser compatibility tables (although test result tables are probably more reliable).

**Comment by ericelliott** [comment]
It seems to me that `requires` can be inferred from the function body. I don't like the idea of manually annotating that stuff, but maybe an rtype generator tool could read your file and generate an interface document similar to the TypeScript DefinitelyTyped files. I do like the idea of being able to see requirements using runtime reflection. rfx could do that by looking at the function body...

> We could have => aliased to returns

Would this provide any advantages?

**Comment by ericelliott** [comment]
> It would be pretty neat to be able to (eventually) generate a minimum poly-fill required for each target environment, assuming all my functions have their ES5 and ES2015 API dependencies noted.

Yes, it would.

**Comment by Mouvedia** [comment]
Well that's part of my documentation currently, that's why I am requesting it. Having to scan the body to extract the information isn't ideal and could be done at runtime anyway.

It's the last feature missing for me to switch to rtype.

> > We could have => aliased to returns
> 
> Would this provide any advantages?

If we were to use returns then it would be in line with throws and requires.
verb + s + :

It's just for consistency if we were to have `requires`.

**Comment by ericelliott** [comment]
:+1:  I like it. I just think it could be generated automatically by rfx and other rtype tools. Happy to add `requires` to the spec:

``` js
A()
  throws: ErrorType
  requires: B
```

**Comment by ericelliott** [comment]
Also willing to take an rfx PR to automatically generate `requires` for the runtime reflection.

**Comment by jokeyrhyme** [comment]
Whether or not a machine populates it, it seems like `requires` probably could be part of the specification.

**Comment by Mouvedia** [comment]
Ill do the PRs tonight.

**Comment by ericelliott** [comment]
Agreed. We need to flesh it out a bit though. =)

``` js
A(aParam: SomeType) => ReturnType,
  throws: ErrorType,
  requires:
    B, // not passed in
    aParam.someMethod // aParam is passed in, someMethod is used.
```

**Comment by ericelliott** [comment]
We can close this issue after a solution gets merged. =)

**Comment by Mouvedia** [comment]
@ericelliott  In your example SomeType should be Object right?

**Comment by jokeyrhyme** [comment]
It seems a bit redundant to have `requires` refer to a property on an argument, when that should already be governed by the type definition for that argument.

`requires`, to me, excels at highlighting global variables, etc that would otherwise go undocumented.

**Comment by Mouvedia** [comment]
I think we shouldn't try to cover everything in the first PR. Let's try to meet the main use case and open new issues for the rest. GTG Ill PR tonight.

**Comment by ericelliott** [comment]
> In your example SomeType should be Object right?

`SomeType` may be an `Object` that has a more specific interface than the generic `Object` type. =)

**Comment by Mouvedia** [comment]
Won't the usage of the comma without a way to group the dependencies be a problem for the parser?
We need brackets else we won't be able to switch throws and requires:

```
A(aParam: SomeType) => ReturnType,
  requires:
    B,
    C
  throws: ErrorType
```

And I am against enforcing the order.

**Comment by Mouvedia** [comment]
#36

**Comment by ericelliott** [comment]
> Won't the usage of the comma without a way to group the dependencies be a problem for the parser?

No. `throws` and `requires` can be reserved words that automatically terminate the previous block.

**Comment by Mouvedia** [comment]
@ericelliott Are you being notified by mail? You should check the issue in your browser.
Anyhow the second point still requires to group them somehow.

**Comment by Mouvedia** [comment]
@ericelliott you mean `throws[\s]*:` and `requires[\s]*:`?
A function could be named throws (`throw` is a reserved name not throws).

What would happen if someone use requires twice? Should we keep the last one or tally them all?

**Comment by ericelliott** [comment]
> A function could be named throws

Sure, but shouldn't this be a syntax error?

``` js
A(aParam: SomeType) => ReturnType,
  throws: ErrorType,
  randomFunctionName:
```

Or is there some circumstance where that would make sense?

**Comment by Mouvedia** [comment]
Well it's not on scope with rtype, and we both know that the parser will handle it fine.
So I think it's time to merge #36.
