### ISSUE TITLE
Predicate builtin

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/rtype#38]
Accidentally self-merged a proposal for a [Predicate builtin type](https://github.com/ericelliott/rtype/blob/master/README.md#the-predicate-type). Thoughts are welcome.

**Comment by Mouvedia** [comment]
Remind me of [contractual](https://github.com/codemix/contractual).

**Comment by ericelliott** [comment]
Interesting. Maybe rtype should return a full contract instead of a simple predicate?

**Comment by Mouvedia** [comment]
If you are unsure you should revert your commit for now and add a new branch for this feature.

**Comment by ericelliott** [comment]
Well, I'm sure I want a `Predicate` builtin. I'm already using it all the time to describe rfx and rtype related things. =)

**Comment by ericelliott** [comment]
Maybe I'll just close this. If anybody has any concerns, feel free to reopen or file a new issue.

**Comment by Mouvedia** [comment]
Why is the type `Any[]` and not `Any`?

**Comment by Mouvedia** [comment]
rtype shouldn't be tightly coupled to rfx imho. It needs to be all purpose and adapt to any tool.

**Comment by ericelliott** [comment]
> rtype shouldn't be tightly coupled to rfx imho. It needs to be all purpose and adapt to any tool.

It isn't, but rfx uses rtype.
