### ISSUE TITLE
Add a TOC

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#39]
PR are welcomed. Just notify us beforehand.

**Comment by ericelliott** [comment]
:+1: See [doctoc](https://github.com/thlorenz/doctoc).

**Comment by tomek-he-him** [comment]
There’s also https://git.io/doxie. Not drop-in as _doctoc_ is but totally flexible if we need flexibility. See https://git.io/git-tips, https://git.io/tape-css and https://git.io/-npm-scripts for usage examples.

(Sorry for the shameless self-ad! 😃)

**Comment by ericelliott** [comment]
Cool. You want to take this one? =)

**Comment by tomek-he-him** [comment]
Yup, I’ll have a go!

Just give me a week or two – I’m short on time at work (where we use rtype) – and even shorter after hours! 😃

**Comment by ericelliott** [comment]
Cool.

**Comment by tomek-he-him** [comment]
_doxie_ is good if you have data (e. g. an _rtype_ AST) and want to render it into markdown.

Since we have a hand-crafted readme, _doctoc_ looks like the right tool for the job.
