### ISSUE TITLE
Needs an example right near the start of README.md

### ISSUE THREAD

**Issue by SteveALee** [ericelliott/rtype#41]
I really want to see what it looks like and what it can do before reading all the details. Probbaly after "Why" section.

**Comment by ericelliott** [comment]
Done. Look good?

**Comment by SteveALee** [comment]
:+1:
What took you so long? :)
That's helps thanks.

Next a full example hello world?

**Comment by ericelliott** [comment]
Open to a PR for Hello, world using rfx. =)
