### ISSUE TITLE
tokeniser, parser and transpiler thoughts

### ISSUE THREAD

**Issue by jokeyrhyme** [ericelliott/rtype#46]
I've been looking at Acorn: https://github.com/ternjs/acorn
Also, it turns out so have the ESLint crew: http://eslint.org/blog/2015/12/espree-3-alpha-1-released/

If we pick an extensible ES2015 parser like Acorn, espree or [esprima](https://github.com/jquery/esprima), then we _might_ have an easier time dealing with predicate literals (which are ES2015 code).

Another thought I've had is that we could approach rtype like JSX, and provide a [babel](https://github.com/babel/babel) plugin that identifies rtype documentation and transpiles it into an executable predicate.

**Comment by ericelliott** [comment]
:+1: I'm on board with Acorn.

Babel plugin is also a cool idea, though obviously that deserves its own repo.

**Comment by jokeyrhyme** [comment]
I've asked about this on Babel's Slack, but haven't got any bites yet: https://babeljs.slack.com/archives/discussion/p1449008263007196

If we're ultimately generating ES2015 or ES5 code from an rtype document anyway, then maybe we don't even need an intermediate AST?

**Comment by ericelliott** [comment]
Fair point. We could probably just create a JavaScript representation of all the type data in the signature. =)

**Comment by jokeyrhyme** [comment]
Okay, so it doesn't look like babel plugins can introduce new syntax, so I think Acorn is the way to go for the first step: https://github.com/thejameskyle/babel-plugin-handbook/issues/21

**Comment by jokeyrhyme** [comment]
https://babeljs.slack.com/archives/discussion/p1449450551008347
