### ISSUE TITLE
Add usage and definition examples [named signatures]

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#48]
cf https://github.com/ericelliott/rtype/issues/47#issuecomment-161842989

use case: reuse the signature several times in your documentation (it would act like a mixin of some sort)

**Comment by ericelliott** [comment]
There are examples of named signatures scattered all over the docs. Maybe you can open a PR that would clarify your thoughts a bit. =)

**Comment by Mouvedia** [comment]
Are you reusing the function name for the name of the signature?
I don't think that's appropriate.

You could have 2 functions who do 2 very different things and hence using the name of the former for the latter wouldn't be adequate in that case cause the name would have absolutely nothing to do with the signature but everything to do with what the originator does.

**Comment by ericelliott** [comment]
Yeah, I thought that's what you meant, but there really isn't a concept of a "function name" in rtype. Everything is really an `interface`. Sometimes named, sometimes not.

Interface names _may_ correspond 1:1 with actual function names... or not.

In code, interfaces get associated with actual functions using a library such as [rfx](https://github.com/ericelliott/rfx).

In other words, this is totally valid:

``` js
calculate(...numbers: Number[]) => Number
```

```
const sum = rfx({
  type: `calculate`,
  fn: (...numbers) => numbers.reduce((a, b) => a + b)
});
```

```
const product = rfx({
  type: `calculate`,
  fn: (...numbers) => numbers.reduce((a, b) => a * b)
});
```

**Comment by Mouvedia** [comment]
> Interface names may correspond 1:1 with actual function names... or not.

You need to explain that clearly in the documentation.

How do you use that name once the signature has been declared?

**Comment by ericelliott** [comment]
> How do use that name once the signature has been declared?

I don't understand the question. It's an interface. You use it exactly the same way you would use any other interface. Interface and type are synonyms in this context. =)

**Comment by ericelliott** [comment]
In other words:

``` js
validator(...inputs: Array[]) => Boolean

validateForm(form: Object, validator) => Boolean
```

**Comment by Mouvedia** [comment]
Well if you think it's evident I guess Ill close this issue.

**Comment by ericelliott** [comment]
[this PR might help](https://github.com/ericelliott/rtype/pull/45)

If you have any other specific suggestions, I'm open to them. =)

Maybe an example of using a named signature as a type in another signature?

**Comment by Mouvedia** [comment]
The 1:1 situation can be confusing at first, so you should probably edit the examples that use `functionName` and put something more generic like `signatureName`.

**Comment by ericelliott** [comment]
I'm cool with that. Want to open a PR?

**Comment by Mouvedia** [comment]
Id prefer if you did, you know much more about the lingo than me.

**Comment by ericelliott** [comment]
I may not have time to get to it soon. ¯\_(ツ)_/¯

**Comment by Mouvedia** [comment]
@ericelliott #49
