### ISSUE TITLE
anything we can learn from marijnh/getdocs ?

### ISSUE THREAD

**Issue by jokeyrhyme** [ericelliott/rtype#50]
https://github.com/marijnh/getdocs

**Comment by Mouvedia** [comment]
https://github.com/marijnh/getdocs#tags

I like this part.

**Comment by ericelliott** [comment]
Documentation and types are only loosely related. I'd prefer to keep stuff that is clearly for documentation purposes out of the type spec, and use other libs/tools, instead. For example, [rfx](https://github.com/ericelliott/rfx).

**Comment by Mouvedia** [comment]
I think we could have something like ecmascript version tags.

```
ES 1–3, ES5, ES5.1, ES6 | ES2015, ES7, JScript 1.0–9.0, JavaScript 1.0–1.8.5, E4X
```

@ericelliott I agree we should make one thing well and nothing more.

**Comment by tomek-he-him** [comment]
:runner: Late to the party perhaps. But I’ve been using _rtype_ (and the similar _jsig_) alongside the _JSDoc_ syntax to reuse existing tools. I get tags and HTML rendering before all that is ready in _rfx_. Example: https://github.com/parametric-svg/-/blob/bd51a6ac44400562939d21fe1764428281bf70d1/packages/patch/index.js#L8-L29.

So :+1: to @ericelliott!

**Comment by Mouvedia** [comment]
@ericelliott this should be added to https://github.com/ericelliott/rtype#references

**Comment by ericelliott** [comment]
What should be added?

**Comment by Mouvedia** [comment]
`- [getdocs](https://github.com/marijnh/getdocs)`

**Comment by ericelliott** [comment]
Sure.
