### ISSUE TITLE
Literal type default

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#56]
https://github.com/ericelliott/rtype#literal-types

```
method: 'GET' | 'HEAD' | 'DEL' | 'POST' | 'PUT' | 'PATCH',
```

How can I display in my documentation that 'GET' is the default?

**Comment by ericelliott** [comment]
``` js
method = 'GET': 'GET' | 'HEAD' | 'DEL' | 'POST' | 'PUT' | 'PATCH'
```

**Comment by Mouvedia** [comment]
@ericelliott in that case we don't need the value being listed in the enum:

```
method = 'GET': 'HEAD' | 'DEL' | 'POST' | 'PUT' | 'PATCH'
```

It's inferred right?

**Comment by ericelliott** [comment]
I think it's probably better to include the default in the enum, for clarity.

**Comment by Mouvedia** [comment]
If it's not inferred that means we can have a function that throws if you pass it the default value but by passing it nothing it uses the default value itself.

e.g.

```
// paramName = 'thatWillThrow': 'thatWillNot' | Void`

f() // does not throw
f('thatWillNot') // does not either
f('thatWillThrow') // throws
```

Is this correct?
Should we cover this?

**Comment by ericelliott** [comment]
It could be an early error if there's a type mismatch between the default value and the specified type:

``` js
paramName = 'thatWillThrow': 'thatWillNot' | Void` // parse error
```

That would also cover this case:

``` js
paramName = 1: String // parse error
```

**Comment by Mouvedia** [comment]
It's not worth the effort because it's confusing and hence error prone.

**Comment by Mouvedia** [comment]
@ericelliott does it work in the same way for an interface?

```
interface Options {
  method = 'GET': /GET|HEAD|DELETE|POST|PUT|PATCH/i,
  …
}
```

**Comment by tomek-he-him** [comment]
@Mouvedia there’s surely nothing against that. Though I’d wrap the RE with a `^` and `$` – otherwise `'GO GET SOME BREAD'` would pass. :smiley:

**Comment by ericelliott** [comment]
``` js
interface Options {
  method = 'GET': /GET|HEAD|DELETE|POST|PUT|PATCH/i,
  // …
}
```

Is valid. @tomekwi makes a good point. Note that you don't have to wrap every option. You can group them all:

``` js
interface Options {
  method = 'GET': /^(GET|HEAD|DELETE|POST|PUT|PATCH)$/i,
  // …
}
```
