### ISSUE TITLE
case sensitivity [string]

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#57]
use case: enum (type string)

How do we display this information in a clear and concise way?
 I would like to avoid a regular expression solution?

**Comment by ericelliott** [comment]
Currently we don't have syntax for case insensitivity other than regex literals:

``` js
foo: /foo|bar|baz/i
```

Is there a good reason that the regex literal syntax is undesirable for your use-case?

**Comment by Mouvedia** [comment]
``` javascript
method: /get|head|delete|post|patch|put/i,
```

It's not that bad after all.

**Comment by ericelliott** [comment]
Great. =)
