### ISSUE TITLE
assumes keyword

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#58]
```
// GTE ES7
signatureName()
  => Type,
  assumes: ES7

// ES3, ES5+
signatureName()
  => Type,
  assumes: ES3

// ES6+, E4X
signatureName()
  => Type,
  assumes: ES6, E4X
```

We would have 4 types allowed:
- ES 1–3, ES5, ES5.1, ES6 | ES2015, ES7
- JScript 1.0–9.0
- JavaScript 1.0–1.8.5
- E4X

**Comment by ericelliott** [comment]
This could get crazy, and I don't think it belongs in the type spec. Seems like it should be metadata at the package level, IMO.

E4X is a defunct standard proposal, AFAIK, and its only surviving incarnation is JSX. Is there a standard revival I don't know about?

I don't think we'd need types for ES <5, or JavaScript 1 - 1.8.5. Let's stick to ES\* and just use the official year names (ES2015, ES2016, etc...)

**Comment by Mouvedia** [comment]
Code exists in E4X (Mozilla stuff for the most part) so we need to have it.
I disagree on not having ES less than 5; we need to cover every versions. Again documentation exists for legacy code.
It could be useful either on the file level or the function signature level.

**When would I use it?**
If the requires field was filled with stuff (e.g. too many polyfills) regarding a version of ecmascript.
Id just add one value in the assumes field and be done with it: the conformity would be documented concisely.

**Comment by tomek-he-him** [comment]
@Mouvedia, there’s an interesting discussion about documenting polyfills on JS forums since https://github.com/jsforum/jsforum/issues/5#issuecomment-162169591. The emerging consensus seems to be “take the burden off the developer and favor automatic feature detection”. I agree with @ericelliott that this doesn’t belong to _rtype_. If anywhere then rather _rfx_.

By the way, I’m not a great fan of `requires` either.

**Comment by tomek-he-him** [comment]
> Code exists in E4X (Mozilla stuff for the most of it) so we need to have it.

Code exists for IE 10-, but we’ve decided on not worrying about it. A good rule of thumb I’ve learned over the years is “only implement features someone really needs”. So if someone has an idea for a feature, a valid use-case and asks for it, only then we should worry.

**Comment by ericelliott** [comment]
Yep. I really think this is better handled at the module level anyway, perhaps in `package.json`. =)

**Comment by Mouvedia** [comment]
> A good rule of thumb I’ve learned over the years is “only implement features someone really needs”.

Sorry but a lot of people would disagree with you on that, including me.
