### ISSUE TITLE
Anonymous Optional Parameters

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#63]
Currently we have to put the `?` everywhere it's needed:

```
request(Options? | Request? | AnotherThing? | Etc?)
```

Couldn't we just introduce a new syntax that distributes the `?`?

```
request?(Option | Request | AnotherThing | Etc)  // A

//or

request ?(Option | Request | AnotherThing | Etc) // B

//or

request(Option | Request | AnotherThing | Etc)?  // C

//or

request((Option, Request, AnotherThing, Etc)?)   // D
```

Of course, that would be only possible if all parameters are optional.

**Comment by ericelliott** [comment]
Pretty sure I've addressed this somewhere else, but OK:

All of those examples use `|` syntax, which means that  all your `request` examples have a single parameter. To make it optional, just give it a name:

``` js
request(input?: Option | Request | AnotherThing | Etc)
```

But it looks to me like this was not your intention, and all of those options are supposed to be different parameters?

```
request(Option?, Request?, AnotherThing?, Etc?)
```

And now you want to group them together and declare that they're all optional at the same time?

Maybe like this (similar to regex groupings)?

``` js
request((Option, Request, AnotherThing, Etc)?)
```

Or, with destructuring & parameter names:

``` js
request({ (option: Option, request: Request, foo: AnotherThing, bar: Etc )? })
```

Keep in mind, one of our stated design goals is to make reading signatures as intuitive as possible for people already familiar with JavaScript. I could see this getting confusing fast. Sometimes saving a few keystrokes is not worth the loss in readability. I'll wait for others to chime in, but my vote: :-1:

**Comment by Mouvedia** [comment]
> But it looks to me like this was not your intention, and all of those options are supposed to be different parameters?

You guessed correctly.
It has only one drawback: if you decide to add one required parameter the signature will have to be refactored.

Ill add your first proposal as D.

**Comment by ericelliott** [comment]
> It has only one drawback: if you decide to add one required parameter the signature will have to be refactored.

No, it wouldn't. Just add it outside the grouping:

``` js
request(requiredParam, (Option, Request, AnotherThing, Etc)?) => RequestObject
```

**Comment by Mouvedia** [comment]
```
request(Options? | Request?)

//vs

request((Options | Request)?) // Do we really need the extra pair of parentheses?
```

What about

```
request(Options ? Request)
```

?

It's surprisingly clear.
But it will become unreadable if it's followed by a typed parameter (which use `:`).

```
request(Options ? Request, paramName: Type) // ternary?!
```

**Comment by ericelliott** [comment]
``` js
request(Options? | Request?)
```

Remember, the `|` already has a union type meaning. I think you mean:

``` js
// Not grouped
request(Options?, Request?)

// Grouped
request((Options, Request)?)
```

> What about

``` js
request(Options ? Request)
```

What if you wanted 3 or more?

You're right that the last example is unreadable.

**Comment by ericelliott** [comment]
I'm still leaning towards _no grouping syntax_, because I think it adds more problems than it solves.

**Comment by Mouvedia** [comment]
@ericelliott Wait you mean that currently if you have a function that takes one parameter which can be either of type Request (a type of Object) or Options (an user interface which is also an object), we don't have a way to express it using `|`?
If so this is a feature request not an enhancement.

> What if you wanted 3 or more?

Just add more `(Options ? Request ? Other)` ?

**Comment by ericelliott** [comment]
> Wait you mean that currently if you have a function that takes one parameter which can be either of type Request (a type of Object) or Options (an user interface which is also an object), we don't have a way to express it using |?

Yes, you can express that using `|`, hence my first response:

> All of those examples use `|` syntax, which means that **all your request examples have a single parameter**. To make it optional, just give it a name:

``` js
request(input?: Option | Request | AnotherThing | Etc)
```

Done. They're grouped automatically because there's really only one parameter here, and it's optional.

**Comment by Mouvedia** [comment]
@ericelliott OK maybe it wasn't clear but you can have nameless parameters. In my case it would be useful because the name of the interface would probably match the name of the parameter. So my question is, is this legal?

```
request(?: Request | Options)
```

I think it should. It's simple and probably won't bother the parser much.
At least that's how I am gonna document it for my API. I wish it could be valid Rtype so that I don't deviate too much.

**Comment by ericelliott** [comment]
> Is this legal?

``` js
request(?: Request | Options)
```

Not yet, but it could be. I suppose the comma creates enough separation that it doesn't look too ambiguous with other parameters hanging around:

```
request(foo, ?: Request | Options)
request(foo, ?: Request | Options, ?: Bar | Baz)
```

If you want to take a crack at a PR for "Optional Anonymous Parameters", I'd consider it. Don't mention "grouping" or "sharing" the `?` though, because that's not what's happening here. This is a **single optional parameter** that is a union type. In fact, please don't use a union type example. Keep it simple. 

For example, maybe a toggle function with an optional boolean parameter to force the toggle state:

``` js
toggle(state: Object, ?: Boolean) => Object
```

**Comment by Mouvedia** [comment]
Alright Ill do that this week.

**Comment by Mouvedia** [comment]
@ericelliott #69

**Comment by maiermic** [comment]
I just don't get what an _anonymous optional parameter_ is? How is it different to an [optional parameter](https://github.com/ericelliott/rtype#optional-parameters)? May you please give a JavaScript example.

**Comment by ericelliott** [comment]
An anonymous optional parameter has no name.

**Comment by maiermic** [comment]
Do you mean the [arguments object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) or respectively [rest parameters](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Functions/rest_parameters)?

``` JS
function myFunction(parameterWithName, ...parametersWithoutName) {
  // var parameterWithoutName = arguments[1];
  var parameterWithoutName = parametersWithoutName[0]
  // ...
}
```

Is there another way to declare an optional parameter without name?

**Comment by ericelliott** [comment]
@maiermic - Sometimes parameters have pretty useless names like `input` or `obj` that don't add any additional information to an API. In those cases, it should be legal to leave the names out of the signature documentation (remember, rtype isn't just about static analysis - it's also used for documentation).

Example:

``` js
isPlayerInstance(obj: Any) => Boolean
```

... can be written like this:

``` js
isPlayerInstance(Any) => Boolean
```

**Comment by maiermic** [comment]
Your example

> ```
> isPlayerInstance(Any) => Boolean
> ```

is not an optional parameter, but I see what you mean.

How would you call the example

> ```
> request(foo, ?: Request | Options, ?: Bar | Baz)
> ```

without the optional parameter of type `Request | Options` but with the last of type `Bar | Baz`?

**Comment by ericelliott** [comment]
``` js
request(foo, undefined, bar);
```

**Comment by Mouvedia** [comment]
By that @ericelliott probably means that you are deciding to pass `null`.
Anyhow the examples in the README are pretty clear.

The only thing missing is covering the case of an anonymous parameter that has a default value.

**Comment by Mouvedia** [comment]
@ericelliott I disagree, it defaults to `undefined` not `null`. Else we would have `| null`. Is it a typo?
Of course you can call it with whatever you want but since `null` is not an object of type Options or Request it will pose a problem. Is `null` the default value when you have a parameter of type (union) object? That would be logical, since `null` is also an object, but it needs to be added to the documentation.

The only thing missing is covering the case of an anonymous parameter that has a default value.
Ill do a PR for that this week. We will discuss the details directly there.

**Comment by ericelliott** [comment]
> an anonymous parameter that has a default value

I think that's taking this a little too far. If you want a default value, just name the param.

**Comment by ericelliott** [comment]
> it defaults to undefined not null

fixed.
