### ISSUE TITLE
Matching names in code:

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/rtype#64]
I propose adding the following suggestions / rules:
## Naming Things

For optimum clarity in type errors and developer tools:
- Type signature names **SHOULD** match function names in the code (optional).
- Function parameter names **SHOULD** match parameter names in the code (optional, not always possible due to function polymorphism).
- Destructured parameter names **MUST** match parameter names in the code.

**Comment by Mouvedia** [comment]
I think this kind of interpretation/guidance should be left to the implementors. We shouldn't aim to produce a bona fide specification.

It's either common sense or too early to add these details IMO; we would have to litter the README with tons of notes for no real immediate gains.

**Comment by ericelliott** [comment]
I definitely see your point. However, I'm in the process of writing developer style guides and using rtype in real project documentation. Maybe these instructions belong in those style guides, but it should be safe to generally imply these things for most/all projects using rtype?

**Comment by Mouvedia** [comment]
Feel free to reopen if you wanna start somewhere, it seemed to me that it would be inconsistent if not done in a systematic manner. Linking to an official style guide instead of having a full-fledged validator could be a first step in the right direction.
