### ISSUE TITLE
Should we have this?

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#68]
[proposal comment](#issuecomment-290916496)

related discussion: https://github.com/Microsoft/TypeScript/issues/3694

**Comment by ericelliott** [comment]
Cool. Looking over a few of their examples, they make a good case (`.bind()`, `.apply()` w/mixins). I'm open to it.

Want to write up a few example use cases?

**Comment by Mouvedia** [comment]
It's not a rhetorical question. This one is out of my league.
I suppose it's missing, that's it.

**Comment by maiermic** [comment]
Yes, we should. `this` is like regular parameters an argument that is passed to a function call. We should be able to type it.

**Things that should be considered:**
- [Defining classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Defining_classes)
  
  > Classes are in fact [functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions), and just as you can define [function expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/function) and [function declarations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function), the class syntax has two components: [class expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/class) and [class declarations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/class)
- regular function call, e.g. `f(42)`
- regular method call, e.g. `obj.f(42)`
- function call with [apply](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply) or [call](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call)
- [bound functions](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Function/bind)
- type inference/analysis/check of `this` in a function expression due to the declaration context
  - top level (depends on environment: Browser, [NodeJS](https://nodejs.org/en/), ...)
  - inner function declaration
  - arrow functions (lexical this)
  - (static) method of (sub-) class
  - property in object literal
  - property assignment to existing object

Ps: I just quickly scaned the TypeScript discussion yet.

**Comment by ericelliott** [comment]
@maiermic In most cases, `this` should not be typed by the function using `this`, but instead, define some typed subset of `this`. Because `this` is determined by the call-site usage, it's impossible for the user of `this` to accurately determine its full exact shape.

**Comment by maiermic** [comment]
> it's impossible for the user of `this` to accurately determine its full exact shape.

@ericelliott Who is the _user of `this`_? The author of the function?

**Comment by Mouvedia** [comment]
What he's saying is that, unless you have a way to declare the executing context, `this` can be (re-)set to anything. So using `this` would require to have its pendant: the context himself declared in the documentation and tightly coupled somehow to the function signature.

That's why it's only useful—without any prior context setting—when the function doesn't expect something in particular.

**Comment by amcdnl** [comment]
In a lot of languages `this` is considered redundant.

**Comment by Mouvedia** [comment]
I am closing this for now and moving it to the backlog: it's not essential for the MVP.

**Comment by maiermic** [comment]
@amcdnl 

> In a lot of languages `this` is considered redundant.

Any example of a language with type annotations where `this` is not bound to the method? In statically typed languages like Java and C# `this` is of the enclosing class or interface type.

**Comment by Mouvedia** [comment]
In light of #120 and the discussion that ensued on #110, I am reopening this.

**Comment by Mouvedia** [comment]
I am gonna re-introduce the problem at hand for the ones dropping by.

The main use case that we need to cover is—[as explained by @ericelliott before](https://github.com/ericelliott/rtype/issues/68#issuecomment-177678013)—being able to restrict the type of "the call-site".

Now here's my take on this (pun intended), I think it would make sense to place it just before the function signature. e.g. `<here> signatureName(paramName: Type) => ReturnType`

If we really want to make it obvious we could reuse something recognizable by any JS dev:
```
// assumes Example has been defined

// either
Example.signatureName(paramName: Type) => ReturnType
// or
Example[signatureName(paramName: Type) => ReturnType]
```

I don't particularly support this proposal. The priority for me is the position/order.
Which means that the introduction of a new operator would do just as well:
```
Example :: signatureName(paramName: Type) => ReturnType

**Comment by ericelliott** [comment]
The `::` syntax seems promising for `this`, mirroring the ECMAScript [This-Binding Syntax proposal](https://github.com/tc39/proposal-bind-operator):

```
// Iterable::first() => a

const first = function () {
  const [a] = this;
  return a;
};

first.call([1,2,3]); // 1
```

**Comment by Mouvedia** [comment]
I forgot about that proposal but now that you remind me I did participate in tc39/proposal-bind-operator#24

I like your example, it's simple and it's reusing a reserved type [that has already been defined](https://github.com/ericelliott/rtype#the-iterable-type), much clearer than mine.

The problem will be the error case. The way it will be handled is tool-dependent hence off-topic in the rtype specification.

**Comment by Mouvedia** [comment]
@ericelliott 

1. Which syntax(es) should be supported?

```
// A
Iterable::first() => a

// B
::Iterable.first() => a
```

I am leaning toward A. Both is also a valid option.

2. Are spaces allowed around `::`?

If so, shouldn't it be recommended?

**Comment by ericelliott** [comment]
I think you're misunderstanding the second syntax. In the TC39 proposal, the `::map()` syntax means that the return value from the previous expression will be bound to `this` inside `map()`.

I'm not sure how we'd use that in Rtype.

**Comment by Mouvedia** [comment]
>```
>obj::func(val)
>// is equivalent to:
>func.call(obj, val)
>
>::obj.func(val)
>// is equivalent to:
>func.call(obj, val)
>```

Are you telling me that https://babeljs.io/docs/plugins/transform-function-bind/#detail is erroneous?

**Comment by ericelliott** [comment]
OK, but not sure how that makes sense.

```js
::obj.func(val)
// is equivalent to:
func.call(obj, val)
// is equivalent to:
obj.func(val)
```

**Comment by Mouvedia** [comment]
The infix `::` corresponds to `this::`.

The real difference between `::object.method` and `object::method` is that `method` is always a property in the former case. It means that B is out the question since our main use case restricts a context: if we kept it as is we would define the method directly without the need of a subset.

So my vote goes to A.

**Comment by Mouvedia** [comment]
Let's forget about the infix `::` for now.

Which example do you prefer between `Iterable :: first() => a` and `Iterable::first() => a`? Why?

**Comment by Mouvedia** [comment]
@ericelliott î

**Comment by Mouvedia** [comment]
You were right [it was a typo](https://web.archive.org/web/20161015184337/http://babeljs.io:80/docs/plugins/transform-function-bind/):
```
::obj.func(val)
// is equivalent to:
obj.func.call(obj, val)
```

**Comment by Mouvedia** [comment]
@ericelliott #137
