### ISSUE TITLE
If the definition is missing use the global object

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#74]
If, for example, the declaration of the custom Date type is missing from the file we should automatically fall back to the global object.

Here's a non-exhaustive list of commonly used objects that inspired me that new rule:
- Set
- Map
- Date
- Error
- Promise

That also means that you can overshadow those type with your own, which can be useful.
In consequence, the [builtin types](https://github.com/ericelliott/rtype#builtin-types) will be reserved types—if it's not already the case.

**Comment by tomek-he-him** [comment]
I remember a very similar discussion I had with @ericelliott: #20. The conclusion was something like “it’s difficult or impossible to type-check”.

**Comment by ericelliott** [comment]
We should explicitly add the builtin types and manually create type checkers for them. What didn't work about the previous PR is the concept of automatically falling back on any existing constructor, because you can't count on constructors to reliably type check instances.

**Comment by ericelliott** [comment]
I'm open to PRs that add all the built-in constructors as built-in types.

**Comment by Mouvedia** [comment]
I am against the idea of having a huge list of builtin types.

I was leaving the implementation aside but you are right, type-checking must be granular.
What I would support is a separate repository for extra builtins which would contain the type checkers and their corresponding definitions.

**Comment by ericelliott** [comment]
I think these would be useful:
- Date
- Error
- Promise

Set and Map are likely to be subtyped by users to have a particular shape if they care about the shape at all.. but I am not sure there's a great reason not to include them?

**Comment by Mouvedia** [comment]
@ericelliott  What about RegExp and Proxy?

I see the potential but I am a firm believer of the KISS principle.
I originally opened this issue to avoid the never ending expansion.

You should close this issue and open a new one listing potential additions.
