### ISSUE TITLE
add Gitter chat room

### ISSUE THREAD

**Issue by maiermic** [ericelliott/rtype#75]
Please add a [Gitter](https://gitter.im) chat room to enable contact with the contributors.

**Comment by Mouvedia** [comment]
#83

**Comment by ericelliott** [comment]
@Mouvedia Tip: If you don't want me to re-open issues you close, please wait until the fixes are merged to close the issues. ;)

**Comment by Mouvedia** [comment]
PR are issues hence why I always close what I consider redundant issues.
I thought that once a PR is initiated the discussion needs to continue there.

That's my way of handling things. I guess you prefer separating general discussions from the code review itself.

**Comment by ericelliott** [comment]
> PR are issues hence why I always close what I consider redundant issues.

PRs are a way of reviewing and discussing a specific implementation.

> I thought that once a PR is initiated the discussion needs to continue there.

Discussion of the specifically proposed implementation happens there, but what if you need to close the PR in favor of a different solution? You have to re-open the issue to continue tracking?

> That's my way of handling things.

Maybe so, and I appreciate your help and input, but I'm the project maintainer, and I need to be able to track open issues at a glance, and I can't do that if you keep closing them prematurely. =)

**Comment by ericelliott** [comment]
@Mouvedia Another tip: if you add text like `Closes #6999` to the PR description, it will automatically close the issue _after_ the fix is merged.

**Comment by Mouvedia** [comment]
> @Mouvedia Another tip: if you add text like Closes #6999 to the PR description, it will automatically close the issue after the fix is merged.

Now that's the way to go.
