### ISSUE TITLE
Sub builtin types

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#76]
This a followup of #74

`Object`
- Set
- Map
- Date
- Error
- Promise
- RegExp
- Proxy

`Function`
- Predicate

**Comment by ericelliott** [comment]
I'm fine with adding any or all of these.

**Comment by Mouvedia** [comment]
@ericelliott #78

**Comment by ericelliott** [comment]
Let's close this after we merge the changes. =)

**Comment by Mouvedia** [comment]
You sure love to reopen the issues I close :)

**Comment by ericelliott** [comment]
Yep. I like to know when things still need following up on. =)
