### ISSUE TITLE
constraints on generic type arguments

### ISSUE THREAD

**Issue by maiermic** [ericelliott/rtype#82]
# constraints on generic type arguments

There a several common ways to restrict generic type arguments in other languages that might be considered as inspiration for rtype's generics (see discussion about generic types in #55 and #80).
## C&#35;

From [Constraints on Type Parameters (C# Programming Guide)](https://msdn.microsoft.com/en-us/library/d5x73970.aspx):
- `where T : class` The type argument must be a reference type; this applies also to any class, interface, delegate, or array type.
- `where T : <base class name>` The type argument must be or derive from the specified base class.
- `where T : <interface name>` The type argument must be or implement the specified interface. Multiple interface constraints can be specified. The constraining interface can also be generic.
## Scala

> An upper type bound `T <: A` declares that type variable `T` refers to a subtype of type `A`.
> -- [Upper Type Bounds](http://docs.scala-lang.org/tutorials/tour/upper-type-bounds.html)

> The term `T >: A` expresses that the type parameter `T` or the abstract type `T` refer to a supertype of type `A`.
> -- [Lower Type Bounds](http://docs.scala-lang.org/tutorials/tour/lower-type-bounds)
## Java

> A type variable with multiple bounds is a subtype of all the types listed in the bound. If one of the bounds is a class, it must be specified first
> `<T extends A & B & C>`
> -- [Bounded Type Parameters](https://docs.oracle.com/javase/tutorial/java/generics/bounded.html)

> In generic code, the question mark `?`, called the wildcard, represents an unknown type.
> -- [Wildcards](https://docs.oracle.com/javase/tutorial/java/generics/wildcards.html)

> The upper bounded wildcard, `<? extends Foo>`, where `Foo` is any type, matches `Foo` and any subtype of Foo.
> -- [Upper Bounded Wildcards](https://docs.oracle.com/javase/tutorial/java/generics/upperBounded.html)

**Comment by ericelliott** [comment]
I think it's pretty clear that the writing is on the wall, and we need to scrap Java / TypeScript style generics in favor of Haskell-style typeclasses. See #120
