### ISSUE TITLE
Iterable

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#88]
#### The `Iterable` Type

Arrays, typed arrays, strings, maps and sets are iterable. Additionally any object that implements the @@iterator method can be iterated.

```
interface IterableObject {
  [Symbol.iterator]: () => Iterator
}

interface Iterator {
  next() {
    done: Boolean,
    value?: Any
  }
}

(paramName: Iterable) => Void
// Is equivalent to
(paramName: Array | TypedArray | String | Map | Set | IterableObject) => Void
```

**Comment by maiermic** [comment]
According to the [MDN JavaScript reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) the property `[Symbol.iterator]` is

> A zero arguments function that returns an object, conforming to the iterator protocol.

which means

> An object is an iterator when it implements a **next()** method with the following semantics:



> A zero arguments function that returns an object with two properties:
> - done (boolean)
>   - Has the value true if the iterator is past the end of the iterated sequence. In this case value optionally specifies the return value of the iterator. The return values are explained here.
>   - Has the value false if the iterator was able to produce the next value in the sequence. This is equivalent of not specifying the done property altogether.
> - value - any JavaScript value returned by the iterator. Can be omitted when done is true.

**Example:** Default iterator of `String`:

``` js
var someString = "hi";
var iterator = someString[Symbol.iterator]();

iterator.next(); // { value: "h", done: false }
iterator.next(); // { value: "i", done: false }
iterator.next(); // { value: undefined, done: true }
```

Thus, a more expressive type of `IterableObject` is:

``` TS
interface IterableObject {
  [Symbol.iterator]: () => IteratorObject
}

interface IteratorObject {
  next: () => { done: Boolean, value?: Any }
}
```

Both types can be even more expressive if we have generics (see issues #55 and #80).

**Comment by Mouvedia** [comment]
@maiermic I didn't want to go that far in the example.
Ill add your modifications to the upcoming PR.

You have a typo: it should be `interface Iterator`.

**Comment by maiermic** [comment]
@Mouvedia Do you mean I should rename `IteratorObject` to `Iterator`?

**Comment by Mouvedia** [comment]
``` TS
interface IterableObject {
  [Symbol.iterator]: () => Iterator
}

interface Iterator {
  next() {
    done: Boolean,
    value?: Any
  }
}
```

**Comment by maiermic** [comment]
I've adopted your naming style. Why didn't you call your interface `Iterable` instead of `IterableObject`?

**Comment by Mouvedia** [comment]
@maiermic did you check my example? It's only used for iterable objects. The all encompassing `Iterable` is the new type.

**Comment by maiermic** [comment]
Sorry, I was a blockhead :laughing:

That's beacause in my understanding `IterableObject` is implemented by `Array`, `TypedArray`, `String`, `Map` and `Set`. Thus, you don't have to define `Iterable` as an union type `Array | TypedArray | String | Map | Set | IterableObject`.

**Comment by Mouvedia** [comment]
`IterableObject` is defined only to help understanding the second signature in the example.

**Comment by Mouvedia** [comment]
@maiermic `IterableObject` is locally defined only to help understanding the second signature in the example. BTW using the union makes it even more precise.

@ericelliott #92
