### ISSUE TITLE
static keyword

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#90]
### Static types

By prefixing the keyword `static` to a type you are limiting the (re)binding of a variable to that specific type.

```
example(paramName: static Number) => Any

// valid
function example(num) {
  return ++num;
}

// invalid
function example(num) {
  num = 'test'; // this line throws
  return num;
}
```

inspiration: http://stackoverflow.com/q/30004233/248058

**Comment by maiermic** [comment]
Static is not needed:

``` JS
example(paramName: Number) => Any

function example(num) {
  num = 'test'; // error: can not assign value of type String to variable of type Number
  return num;
}
```

**Comment by Mouvedia** [comment]
@maiermic Of course it is needed. It's javascript.

**Comment by maiermic** [comment]
Well, I'm talking about static type checking.

**Comment by Mouvedia** [comment]
@maiermic You need to understand that currently we are just checking if you are passing the right parameters to the function.

My proposal would be stricter in the handling of the variable _in_ the function itself.

**Comment by Raynos** [comment]
@Mouvedia 

Any type checker would have this `static` behaviour by default.

**Comment by Mouvedia** [comment]
@Raynos You could probably have an option to set it globally.
But a granular approach is necessary if we want that feature.

**Comment by ericelliott** [comment]
Shouldn't static be implied? If you want to allow other types, shouldn't you use a union type for that?

**Comment by Mouvedia** [comment]
> If you want to allow other types, shouldn't you use a union type for that?

I don't know what you mean by that. You should come on Gitter we discussed about a global per-file opt-in.

**Comment by ericelliott** [comment]
This `static` behavior you're asking for is assumed and built-in behavior for rtype.
