### ISSUE TITLE
anonymous parameter default value

### ISSUE THREAD

**Issue by Mouvedia** [ericelliott/rtype#93]
```
// named parameter
(num = 42: Number) => Void

// proposal A
(42: Number) => Void

// proposal B
(=42: Number) => Void
```

I don't support B: the `=` seems nonsensical if the parameter name is omitted.

**Comment by ericelliott** [comment]
Proposal a looks like a literal type. Requires special rule & lookahead. I would discourage anonymous parameters with default values, but if we support them, we should use proposal B.

**Comment by Mouvedia** [comment]
@ericelliott 

```
// proposal C
(Number = 42) => Void
```

**Comment by ericelliott** [comment]
Proposal C is much better, but definitely needs special parsing rules. B would probably work right now with a properly implemented parser based on the current spec.

Maybe B = legal (but undocumented), C gets documented and recommended, but pushed to a future milestone?

**Comment by tomek-he-him** [comment]
Since any parameter with a default is [optional](https://github.com/ericelliott/rtype/tree/d0f8a4aff20a39cc7b0be42df0d1151e95a6fcce#anonymous-parameters), this should already work – and it looks good:

``` js
// proposal D
(? = 42: Number) => Void
// …equivalent of
(? = 42) => Void
```

**Comment by Mouvedia** [comment]
> [If a parameter has a default value, most built-in types can be inferred](https://github.com/ericelliott/rtype#reading-function-signatures)

``` js
// proposal A
(42: Number) => Void
// shorthand
(42) => Void

// proposal B
(=42: Number) => Void
// shorthand
(=42) => Void

// proposal C
(Number = 42) => Void

// proposal D
(? = 42: Number) => Void
// shorthand
(? = 42) => Void

// proposal E
(42?: Number) => Void
// shorthand
(42?) => Void
```

**Comment by ericelliott** [comment]
Proposals B & D should be supported by the current spec and should probably be test cases for parsers. Because the feature is already supported, I don't think we need any additional syntax for this in the MVP version.

Can we punt on this and put it in the backlog for a future version?

**Comment by Mouvedia** [comment]
@ericelliott Could you tweet [this](http://www.strawpoll.me/10089519)?

**Comment by ericelliott** [comment]
@Mouvedia 

It seems to me you're trying to solve a problem before it exists. As I mentioned:
1. We already have syntax that should work for now.
2. For most things, supplying a name should be recommended, anyway.

I don't think this belongs in the MVP.

I don't want to spend any more time on this right now. Maybe in a future version. Let's revisit this after we have a parser that works with the MVP rules.

We'll revisit this issue at a more appropriate time.
